### ISSUE TITLE
Glitch in Level 1, Step 5: Fulfillment

### ISSUE THREAD

**Issue by AVGP** [actions-on-google/codelabs-nodejs#1]
The description says to "Turn on Enable webhook call for this intent." but doesn't mention the second setting "Enable webhook call for slot filling".

![image](https://user-images.githubusercontent.com/370246/40442858-fe99a53c-5ec4-11e8-8f81-adc5d9fe40cf.png)

When this setting isn't enabled, testing the intent fails... either the response isn't understood or an error message appears (I can't reproduce the error message though).

**Comment by abhi007tyagi** [comment]
if you enable the slot filling, then you have to handle the capturing of the slot on your own. This does not look the case as mentioned in the codelab.

**Comment by AVGP** [comment]
Aha, strange. The example of the code lab didn't work for me until I did
enable that setting. Maybe I'm mistaken?

Abhinav Tyagi <notifications@github.com> schrieb am Fr., 29. Juni 2018,
18:10:

**Comment by smishra2** [comment]
Hey there @AVGP, sorry for the late response. Enabling the webhook for slot filling should not be necessary, as @abhi007tyagi. Could you double check whether that is the issue, and then re-open this if you are still seeing this issue?

**Comment by abhi007tyagi** [comment]
Agreed with @smishra2  it is not necessary to enable Webhook for slot filling. @AVGP please check the logs that get captured. You can enable and view logs from Agent settings:

![image](https://user-images.githubusercontent.com/12875356/42588814-7f2b8d7e-855c-11e8-9a35-4cddd40fbd2d.png)
