### ISSUE TITLE
Minor text change in "Starting a Conversation"

### ISSUE THREAD

**Issue by ilithium** [actions-on-google/codelabs-nodejs#10]
Just working through this codelab and spotted something quite small:

In "Test the welcome intent" there're a couple of instructions which refer to a screenshot of the Google Assistant Integration. Point 2 reads: "Click Test to update your Actions project and load it into the Actions Console simulator. (If you see a ‘Check auto-preview setting' dialog, you can leave the ‘Auto-preview changes' option is enabled, then click **Continue**.)"

In the image below there isn't a "Continue" action, just "Test" which is the correct link to click.

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
