### ISSUE TITLE
Level 1, Module 5, "Create a Dialog Intent" Step 4 Renamed

### ISSUE THREAD

**Issue by brianbaso** [actions-on-google/codelabs-nodejs#12]
> 4. Under Action and parameters, click **Manage Parameters And Action**.

On Dialogflow this button has been renamed to **Add Parameters And Action**.

**Comment by smishra2** [comment]
Hi @brianbaso, I'm not seeing this text in the Level 1 codelab anymore. Can you reopen if you still see it?
