### ISSUE TITLE
Sample on colours not responding

### ISSUE THREAD

**Issue by APratham** [actions-on-google/codelabs-nodejs#13]
I followed all the instructions given in the Google codelabs but after that I'm facing an error that 'final_response must be set'. Also when I try to test it on my Google Assistant, it leaves the conversation in the middle

**Comment by vinaypuppal** [comment]
I am also facing the same issue

![screen shot 2018-08-02 at 18 19 24](https://user-images.githubusercontent.com/8843216/43584746-e17fcc1c-9680-11e8-8caf-3a4063a14800.png)

**Comment by taycaldwell** [comment]
Hello @APratham,

It looks like a response isn't being sent back from your fulfillment after the intent is triggered.
Can you please double check a couple of things for me?

From the Fulfillment tab of Dialogflow:
1.)  Ensure the Inline Editor is enabled, and is filled in with the fulfillment code provided by the codelab.
2.) Ensure that your fulfillment code has been deployed by clicking the `Deploy` button. Please note that this can take a couple of minutes.

From the Integrations Tab in Dialogflow:
1.) Click `Integration Settings` for the Google Assistant, and ensure `Auto-preview changes` is enabled.

From the Actions on Google Console Simulator:
1.) Click the `Reset` icon in the upper right corner.  This will reset the Simulator.
2.) Click `Change Version`, and verify you are using the latest draft of your project.

If you still run into issues after verifying the above, please let me know and I will try my best to help you with this issue.

Thanks. :)

**Comment by APratham** [comment]
Hi @taycaldwell ,

Thanks a lot for your helpful suggestions. However the app is still not working. I have tried all the steps that you told. Please find below for your reference the entire code from the Dialogflow Fulfillment webhook. There were no versions in the Simulator as it is a basic project (I just copied whatever the tutorial told). below showing the various steps that I have completed. One good thing I found out is that it is possible to test the action directly on my google assistant app. I am sending a screenshot of that as well. Please do help me. I would be really grateful

`'use strict';

// Import the Dialogflow module from the Actions on Google client library.
const {dialogflow} = require('actions-on-google');

// Import the firebase-functions package for deployment.
const functions = require('firebase-functions');

// Instantiate the Dialogflow client.
const app = dialogflow({debug: true});

// Handle the Dialogflow intent named 'favorite color'.
// The intent collects a parameter named 'color'.
app.intent('favorite color', (conv, {color}) => {
    const luckyNumber = color.length;
    // Respond with the user's lucky number and end the conversation.
    conv.close('Your lucky number is ' + luckyNumber);
});

// Set the DialogflowApp object to handle the HTTPS POST request.
exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);`

![snap2](https://user-images.githubusercontent.com/33273990/43677334-ec46774c-981d-11e8-82ab-220fb7eeba0e.PNG)
![snap3](https://user-images.githubusercontent.com/33273990/43677335-ec837f70-981d-11e8-8ab1-dccd1c14918c.PNG)
![snap](https://user-images.githubusercontent.com/33273990/43677336-ecb7983c-981d-11e8-8cba-22453d485302.PNG)
![screenshot_20180804-192522](https://user-images.githubusercontent.com/33273990/43677366-6e9739e8-981e-11e8-9705-9e6f6eb216c0.jpg)

**Comment by NoobOtter** [comment]
Hi guys,

I've the same problem as @APratham . I've done all the requirements and check twice time but it still not work and i've always the same error : " My test app isn't responding right now. Try again soon. "

**Comment by APratham** [comment]
@taycaldwell I'll be on it. I will update this comment if my problem is solved.

**Comment by APratham** [comment]
Hi! Thanks to @NoobOtter my problem is now solved. It was a really tiny mistake but due to that the action was giving out some really funny errors.
