### ISSUE TITLE
Where is the text?

### ISSUE THREAD

**Issue by dandv** [actions-on-google/codelabs-nodejs#16]
Say I found a typo at https://codelabs.developers.google.com/codelabs/actions-1/index.html, how would I fix it?

**Comment by Fleker** [comment]
You can't directly fix a typo in a codelab, as that's not available generally. You can file an issue on this GitHub repo and someone who wrote the codelab can make the fix.

**Comment by dandv** [comment]
Nvm, I found the path on cs.
