### ISSUE TITLE
"Select at least one language..." out of order?

### ISSUE THREAD

**Issue by JudeOsborn** [actions-on-google/codelabs-nodejs#17]
When creating a project step 8 says "Select at least one language for your Action, followed by Update. For this codelab, we recommend only selecting English." 

I do not see this after clicking "Add an action" (step 7). Is it supposed to happen in Dialog flow after clicking Build?

**Comment by taycaldwell** [comment]
This is no longer a step in the Action creation process. This step has been removed from the codelab. Thank you for reporting this.
