### ISSUE TITLE
Missing step in the codelab 2

### ISSUE THREAD

**Issue by surbheesehgal** [actions-on-google/codelabs-nodejs#19]
One step is missing as highlighted in the screenshot.

If the users miss this step, the inline editor will remain enabled and users might not be able to figure out the issue.
<img width="1677" alt="screen shot 2018-09-14 at 11 06 16 am" src="https://user-images.githubusercontent.com/27842227/45567291-3f8c1c80-b80e-11e8-8e3e-8d38c3e0b339.png">

**Comment by taycaldwell** [comment]
This issue is now fixed: https://codelabs.developers.google.com/codelabs/actions-2/#2
