### ISSUE TITLE
Typo in codelab 1

### ISSUE THREAD

**Issue by surbheesehgal** [actions-on-google/codelabs-nodejs#20]
![screen shot 2018-09-14 at 11 15 42 am](https://user-images.githubusercontent.com/27842227/45567789-980fe980-b80f-11e8-9c55-f1a41abe2e9a.png)

Duplicate sentence.

**Comment by taycaldwell** [comment]
This issue is now fixed: https://codelabs.developers.google.com/codelabs/actions-1/#2
