### ISSUE TITLE
Step 4 - Code Lab 2

### ISSUE THREAD

**Issue by surbheesehgal** [actions-on-google/codelabs-nodejs#22]
The below example of 'Implicit invocation' in the console seems to be confusing because the name of the app 'Personal Chef' is specified in the user query. 

![screen shot 2018-09-14 at 11 43 24 am](https://user-images.githubusercontent.com/27842227/45569116-6dc02b00-b813-11e8-9d26-f638f86423ec.png)

**Comment by taycaldwell** [comment]
I don't understand what you are reporting here.

The query "Ok Google, talk to Personal Chef" is an example query for explicit invocation, not implicit invocation.

**Comment by surbheesehgal** [comment]
I'm talking about the implicit invocation as highlighted/marked in the
screenshot. The explanation for 'IMPLICIT' invocation states "Specify
intents that trigger "deep-link" actions in your app, allowing users to
invoke specific functionality, such as "OK Google, ask *Personal Chef *for
a hot soup recipe". Providing good action phrases. Learn more.
<https://developers.google.com/actions/discovery/implicit>" This doesn't
seem to be a valid example of implicit invocation phrase since user is
clearly specifying the name of the 3P app - "*Personal chef*" here.

Please let me know if it's still not clear.

**Comment by taycaldwell** [comment]
I understand now. 

Your concern is that the example provided under the Implicit Invocation section uses a deep-link phrase that specifies the name of the Action explicitly, rather than an implicit invocation that doesn't specify the name.

**Comment by smishra2** [comment]
Hey @surbheesehgal, thanks for this feedback! We'll deliver it to the Dialogflow team and try to make the UI more clear here. In the meantime I'll close this issue as it's unrelated to the codelab itself.
