### ISSUE TITLE
Level 2 step 5 can't get name from google when testting

### ISSUE THREAD

**Issue by dongvanthinh** [actions-on-google/codelabs-nodejs#24]
Hi Guys, 

when i'm testting Level 2 step 5 then 

<img width="456" alt="screen shot 2018-10-08 at 08 52 06" src="https://user-images.githubusercontent.com/4090488/46589761-b9df5200-cad7-11e8-803b-81d7bb974bee.png">

Can i help you plz,

**Comment by geofflangenderfer** [comment]
I'm also having this issue. Any help is appreciated.
