### ISSUE TITLE
Use storage with a WebhookClient object

### ISSUE THREAD

**Issue by dbeqiraj** [actions-on-google/codelabs-nodejs#25]
In the third [Get Started](https://codelabs.developers.google.com/codelabs/actions-3/index.html#4) it tells us how to use storage feature to store user preferences throughout different sessions.

Example:

`conv.user.storage.userName = 'jdoe';`

Can the storage be implemented over a **WebhookClient** object like:

```
const agent = new WebhookClient({ request, response });
agent.user.storage.userName = 'jdoe';
```

If this is not the proper way to use storage with a WebhookClient object, how would it be then?

**Comment by Fleker** [comment]
User storage is a feature exclusive to Actions on Google, and to use it you should use the Actions on Google library.

If you do want to use `WebhookClient`, you can take a look at [the JSON](https://developers.google.com/actions/assistant/save-data#save_data_across_conversations) and respond with JSON directly.

**Comment by smishra2** [comment]
Hi @dbeqiraj, as @Fleker said, the interface you are talking about (`conv.user.storage.userName`) is only available through the [Actions on Google Node.js Client Library](https://developers.google.com/actions/reference/nodejsv2/overview). The **WebhookClient** object you're using is part of the [Dialogflow client library](https://github.com/dialogflow/dialogflow-fulfillment-nodejs), which doesn't have support for all of the Actions on Google features specifically, as Actions on Google is one of many possible integrations with Dialogflow.
