### ISSUE TITLE
firebase deploy error

### ISSUE THREAD

**Issue by dumabg** [actions-on-google/codelabs-nodejs#29]
Can't firebase deploy, appears this error:
Error: Error parsing triggers: Cannot find module 'firebase-admin'

**Comment by Fleker** [comment]
Have you first run `npm install` in the `functions` directory?

**Comment by dumabg** [comment]
Gives this output:

npm WARN saveError ENOENT: no such file or directory, open 'D:\Projectes\assistant\codelabs-nodejs\level2\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Projectes\assistant\codelabs-nodejs\level2\package.json'
npm WARN firebase-functions@2.1.0 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN level2 No description
npm WARN level2 No repository field.
npm WARN level2 No README data
npm WARN level2 No license field.

audited 546 packages in 2.143s
found 0 vulnerabilities

**Comment by Fleker** [comment]
Okay, as long as there's no errors, then it should be good to deploy.

**Comment by dumabg** [comment]
The same error:

```
D:\Projectes\assistant\codelabs-nodejs\level2>firebase deploy
!  functions: package.json indicates an outdated version of firebase-functions.
 Please upgrade using npm install --save firebase-functions@latest in your functions directory.

=== Deploying to 'actions-codelab-a3d59'...

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'firebase-admin'

Try running "npm install" in your functions directory before deploying.

**Comment by Fleker** [comment]
Ah, it looks like you're installing Firebase Functions `2.1.0`, which is higher than the expected `^1.0.2` as listed in the [`package.json`](https://github.com/actions-on-google/codelabs-nodejs/blob/master/level2-complete/functions/package.json) file. The package also has Firebase Admin `^5.12.0`, which is lower than the expected `~6.0.0` noted in the warning above.

**Comment by dumabg** [comment]
I've already done the install, but it doesn't work:

`
D:\Projectes\assistant\codelabs-nodejs\level2>npm install --save firebase-functions@latest

> firebase-functions@2.1.0 postinstall D:\Projectes\assistant\codelabs-nodejs\level2\node_modules\firebase-functions
> node ./upgrade-warning


======== WARNING! ========

This upgrade of firebase-functions contains breaking changes if you are upgrading from a version below v1.0.0.

To see a complete list of these breaking changes, please go to:

https://firebase.google.com/docs/functions/beta-v1-diff

npm WARN saveError ENOENT: no such file or directory, open 'D:\Projectes\assistant\codelabs-nodejs\level2\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Projectes\assistant\codelabs-nodejs\level2\package.json'
**npm WARN firebase-functions@2.1.0 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.**
npm WARN level2 No description
npm WARN level2 No repository field.
npm WARN level2 No README data
npm WARN level2 No license field.

+ firebase-functions@2.1.0
updated 1 package and audited 546 packages in 4.637s
found 0 vulnerabilities
`

**Comment by Fleker** [comment]
You may need to also run `npm install firebase-admin`

Can you run `firebase --version` to see what version it is? The codelab package may need to be updated.

**Comment by dumabg** [comment]
It works!
Thank you very much.

**Comment by Fleker** [comment]
Hang on @dumabg can you run `firebase --version` so we know what you're using and see if we need to update our codelab instructions?

**Comment by dumabg** [comment]
6.1.1

**Comment by villeodell** [comment]
Root cause of this issue would seem to be: https://github.com/firebase/firebase-functions/issues/342
