### ISSUE TITLE
firebase-admin and firebase-functions as devDependencies?

### ISSUE THREAD

**Issue by CoreyCole** [actions-on-google/codelabs-nodejs#31]
https://github.com/actions-on-google/codelabs-nodejs/blob/master/level1-complete/functions/package.json#L16

Are these dependencies required to be packaged up and used during execution of the firebase function? Or would they better be assigned as devDependencies?

**Comment by CoreyCole** [comment]
https://github.com/actions-on-google/codelabs-nodejs/blob/master/level1-complete/functions/index.js#L20

Looks like `firebase-functions` is a prod dependency because it is used in index.js, what about firebase-admin?

**Comment by smishra2** [comment]
Hey @CoreyCole, great question. `firebase-admin` is a required peer dependency of `firebase-functions`. In keeping with Cloud Functions for Firebase code in general, we keep it as part of our dependencies list. This [video](https://youtu.be/DYfP-UIKxH0?t=330) goes over this a little bit.
