### ISSUE TITLE
Level 3 -> restoring an agent through zip

### ISSUE THREAD

**Issue by yagyanshbhatia** [actions-on-google/codelabs-nodejs#33]
I cloned this repository, and as stated here: https://codelabs.developers.google.com/codelabs/actions-3/index.html#2
I tried to restore agent through `export and import` section's `restore agent` and uploaded `codelab-level-two.zip` but it takes forever to upload. 
![screenshot from 2018-12-15 10-05-59](https://user-images.githubusercontent.com/26413062/50039030-3c910a00-0051-11e9-817a-1db7a0d93358.png)
It remains in this state forever. Can't proceed, I'm not sure if its a bug, or I'm doing something wrong.

Any help?

**Comment by entertailion** [comment]
You have to type "RESTORE" in the input field and then press the restore button.

**Comment by yagyanshbhatia** [comment]
Shit. I had the impression that its the progress bar under "codelab-level-two.zip". Thanks for helping me out!
