### ISSUE TITLE
Add an extra step in 'Build Actions for the Google Assistant (Level 1)'

### ISSUE THREAD

**Issue by nuxibyte** [actions-on-google/codelabs-nodejs#35]
After **6. Build > Actions in the left nav.** if the user does not have any actions they need to click the **Add your first action** button in order to show the **Create Action** dialog referred to in **7. On the Create Action dialog...**

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed.

If you think this resolution is in error, please re-open the request with fresh information.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
