### ISSUE TITLE
Level 1, Step 6 wrong answer 

### ISSUE THREAD

**Issue by catafest** [actions-on-google/codelabs-nodejs#39]
after insert the source code in Inline Editor the test on agent don't save the changes .
the response to "Talk to my test app" is "Okay. Getting the test version of my test app.Hi! How are you doing?"

The deploy logs

10:29:36.464 PM | warning | dialogflowFirebaseFulfillment | Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail |  
-- | -- | -- | -- | --

10:29:36.464 PM | warning | dialogflowFirebaseFulfillment | Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail |  
-- | -- | -- | -- | --

**Comment by Fleker** [comment]
You may need to wait for a few seconds for the function changes to be fully ready.
