### ISSUE TITLE
Level 2 Step 5 Suggestions Chip Not showing

### ISSUE THREAD

**Issue by catherinetsang** [actions-on-google/codelabs-nodejs#41]
I was able to complete all levels with no problems with suggestion chips showing up for yes , no chips, but i've not been able to get them to work for the colors.
![image](https://user-images.githubusercontent.com/28896410/53533299-62fb0900-3ac8-11e9-9d9b-61ce2ada19d0.png)

**Comment by maaaaaaaax** [comment]
Hi Catherine! Could you share this (and include your fulfillment code) on StackOverflow? That will help other users who have a similar issue.

**Comment by catherinetsang** [comment]
Thanks for taking a look Max. I shared it [here](https://stackoverflow.com/questions/55087363/suggestions-chips-not-showing-consistently)!

**Comment by catherinetsang** [comment]
@maaaaaaaax just an update that I tried using my device instead and all the suggestion chips show up properly. Apparently another user on StackOverflow regularly sees this issue when using the Simulator. We should edit instructions for codelabs asking users to try it on the device if it doesn't show on simulator and also file a bug for google actions simulator if there isn't one already.

**Comment by MarckK** [comment]
Level 2, Step 5, suggestion chips now showing when using the Simulator. :)

**Comment by sarahdwyer** [comment]
Closing since issue fixed
