### ISSUE TITLE
Unknown error when creating DiaglogFlow agent

### ISSUE THREAD

**Issue by blairkutz** [actions-on-google/codelabs-nodejs#42]
Ater clicking 'create' as part of step 'Create a Dialogflow agent' on page: https://codelabs.developers.google.com/codelabs/actions-1/index.html#2 an error was displayed:

"Unknown error errorid=14f81937-afdf-472a-9bf8-d0e0f8d163a9"

It appears as if everything is working though.

**Comment by PratheeshPJ** [comment]
Is anyone having this error???

**Comment by someonelikeTIM** [comment]
Same
Unknown error errorid=79b15066-d937-4edd-b589-64847d6ba08c

**Comment by someonelikeTIM** [comment]
Tried logging out and starting fresh:
Unknown error errorid=b0353905-b59d-4a5c-b17c-ac2d9fc4e23a

**Comment by Fleker** [comment]
We're aware of an issue affecting project creation. Please see status.cloud.google.com

**Comment by marcz2007** [comment]
I'm getting this error whenever I try to upload a json intent: Unknown error errorid=8d5fabcb-3115-4d3f-af58-a66933dfee11

**Comment by Nikitapande** [comment]
I am getting error as "Unknown error errorid=43c7c230-8ce4-4c75-bfa1-6a6b28bf5efe"

**Comment by Fleker** [comment]
The original project creation bug has been resolved.

**Comment by ejames17** [comment]
im having the same issue

**Comment by vidursatija** [comment]
I'm having this issue as well

**Comment by jawwadturabi** [comment]
I also have experience the same issue

**Comment by jawwadturabi** [comment]
I have fixed this issue! The problem was the intent which I have downloaded was follow-up intent and by default when we select upload intent it upload as a single intent which conflicts.

**Comment by adriancc57** [comment]
> I have fixed this issue! The problem was the intent which I have downloaded was follow-up intent and by default when we select upload intent it upload as a single intent which conflicts.

I'm having the same erro when I try to create the agent, is this your case?

**Comment by vineetfrequent** [comment]
I am also having the same error

**Comment by vineetfrequent** [comment]
@adriancc57 : is this fixed for you?
I am having that issue while creating a new agent

**Comment by fndos** [comment]
I'm also having the same issue by creating a new agent from an existing project:

`Unknown error errorid=c7febd8c-e7a8-424e-aaed-3a2611ef007f`

**Comment by adriancc57** [comment]
@vineetfrequent  nope, I'm still facing the issue, not sure why it's happening, but I'm exploring other option like this app
https://play.google.com/store/apps/details?id=tkstudio.autoresponderforwa&hl=en

**Comment by fndos** [comment]
In my case, I've created a new project from GCP after that a new agent based on that recently created project. It works!
