### ISSUE TITLE
Extra comma in Codelab 2 step 5

### ISSUE THREAD

**Issue by ToniCorinne** [actions-on-google/codelabs-nodejs#45]
Index.js code - 
`// Import the Dialogflow module and response creation dependencies from the 
// Actions on Google client library.
const {
  dialogflow,
  Permission,
  Suggestions,
} = require('actions-on-google');
`

The comma after `Suggestions` needs to be removed.

**Comment by smishra2** [comment]
Hi @ToniCorinne , I assume this is for level2-complete? Thanks for the comment. Javascript supports trailing commas, and in fact it's part of the [Google JS style guide](https://google.github.io/styleguide/jsguide.html).

Let me know if you have more questions.
