### ISSUE TITLE
Error in Followup Intent - Actions on Google Codelab 2, step 7 

### ISSUE THREAD

**Issue by mstahl302** [actions-on-google/codelabs-nodejs#47]
re: https://codelabs.developers.google.com/codelabs/actions-2/index.html#6

I was trying out the followup intent page (listed above.  The dialog would terminate as soon as I entered a color, and I could not enter a followup intent. 

I traced the problem to the sample code created in step 5.  The 'favorite color' intent handler used the conv.close() construct to issue a response.  This immediately terminated the conversation and did not allow for a followup intent. 

I fixed this by replacing the conv.close() with conv.ask().  I also changed the text of the response to add the word "Again?", indicating the user should say "yes" or "no" (in line with the followup intent).

The codelab should be fixed to update the 'favorite color' intent handler as described.

**Comment by mstahl302** [comment]
(FYI, I work at google)

**Comment by maaaaaaaax** [comment]
Hi @mstahl302 - thanks for posting this!

You're correct - if a user tests their action at the end of Step 7 (Add follow-up intents) and before completing Step 8 (Add a custom entity), the conversation will close, like you pointed out. 

I'll propose your solution (and a few others) to the authors. Please open a new issue if you find any other unexpected behavior!

**Comment by maaaaaaaax** [comment]
We've added a tip to the Codelab to clarify:

> Tip: If you test your Action at this point, your conversation ends when you trigger the favorite color intent. This is because the intent's fulfillment currently calls the conv.close method. In the next step, you'll update your fulfillment to call conv.ask instead, which allows the conversation to continue.
