### ISSUE TITLE
https://www.apache.org/licenses/LICENSE-2.0.txt

### ISSUE THREAD

**Issue by Melissa1337** [actions-on-google/codelabs-nodejs#49]
https://opensource.org/licenses/Apache-2.0

**Comment by Melissa1337** [comment]
> https://opensource.org/licenses/Apache-2.0

**Comment by Fleker** [comment]
I'm not sure what you mean through this issue. If you are looking for the license for this codelab, the full text is available in [`LICENSE`](https://github.com/actions-on-google/codelabs-nodejs/blob/master/LICENSE).
