### ISSUE TITLE
Code lab breaks design guideline (serial comma) in step 7

### ISSUE THREAD

**Issue by mscheel** [actions-on-google/codelabs-nodejs#5]
In step 7 "Add follow-up intents", this instruction:

Under **Responses**, add "Which color, indigo taco, pink unicorn or blue grey coffee?" as a **Text response**.

Is missing a comma after "pink unicorn", per the [punctuation design guidelines here](https://designguidelines.withgoogle.com/conversation/style-guide/capitalization-punctuation.html).  The sentence requires a serial/oxford/harvard comma after the second item in the list.

Also, too trivial for it's own issue, but look at the erratic punctuation at Step 8, instruction 6:

```
Under Training phrases, type:

- "indigo taco",
- "tell me about pink unicorn"
- "i want to know about blue grey coffee".

```

The first line has a comma at end, second line has nothing, third has a period.  Either add a comma to second or (my preference, as this is a bulleted list) get rid of all the trailing punctuation, to make it consistent for the reader.

**Comment by qchong** [comment]
Fixed: 
https://codelabs.developers.google.com/codelabs/actions-2/#6
https://codelabs.developers.google.com/codelabs/actions-2/#7
