### ISSUE TITLE
I'm having problem in creating carasouel in (level 3)

### ISSUE THREAD

**Issue by jayesh83** [actions-on-google/codelabs-nodejs#54]
![image](https://user-images.githubusercontent.com/40509714/61125027-3e775a80-a4c6-11e9-9a21-3903093c7599.png)

As you can see in image i've attached when I try to click/type favourite colors name it raises an error saying **" This phone is not responding right now please try again soon! "**

**Comment by taycaldwell** [comment]
Unable to reproduce. Please reopen if you are still running into this issue, and provide more details and error logs.
