### ISSUE TITLE
DialogFlow Tutorial ZIP failure

### ISSUE THREAD

**Issue by xbootnek** [actions-on-google/codelabs-nodejs#57]
The tutorial calls for codelabs-nodejs-level-<one/two>.zip to be downloaded from GitHub when GitHub has only has codelabs-nodejs-master.zip that contains 3 levels. The 3 level ZIP downloads correctly but unzipping gives this error:

"No intents or entities found in file. Make sure that file is a zip archive and that intents and entities are in json format and are located inside intents and entities folders correspondingly."

If folders have to be created in advance of unzipping, some guidance should be given as to where.

**Comment by Fleker** [comment]
You need to upload the `codelabs-nodejs-level-<one/two>` file to Dialogflow through the **RESTORE** option. That is within the larger zip file that you download, within each `level-<x>` folder.

**Comment by xbootnek** [comment]
Thanks; that worked.

For the benefit of the code challenged like me, the instructions could be
made easier to follow. Would you like me to draft something?

Instead of

Select *Restore from zip*. Follow the directions to restore from the
`codelab-level-<one/two>.zip` file in this repo.


Substitute:


Download the codelabs-nodejs-master.zip and unZip it. Find and save or
print the Readme.md file.

In Level-1-Complete, find the file codelab-level-one.zip and save it
somewhere.

In Dialogflow select *Restore from zip* and select codelab-level-one.zip.

Repeat this process for in the folders Level-2-Complete and Level-2-Complete




John Murphy

415-515-3022

**Comment by xbootnek** [comment]
I'm OK with Step 2 and all the other steps to create Actions manually.

My only confusion was with the instructions for the Code Labs 1 & 2 which I
think have incompatibilities and lack clear directions that prevent one (or
at least me) installing the Labs correctly.

John Murphy

415-515-3022

**Comment by taycaldwell** [comment]
Please follow [the steps under **Set up your project and agent**](https://codelabs.developers.google.com/codelabs/actions-2/#3) for further clarification and guidance on how to properly restore a Dialogflow agent using the provided .zip files.
