### ISSUE TITLE
Dialogflow webhook fullfillment

### ISSUE THREAD

**Issue by mrinal2305** [actions-on-google/codelabs-nodejs#63]
I am using a testing handler for calling intent 'test' for testing webhook fullfillment.

    'use strict';

    const functions = require('firebase-functions');
    const {WebhookClient} = require('dialogflow-fulfillment');
    const {Card, Suggestion} = require('dialogflow-fulfillment');

    process.env.DEBUG = 'dialogflow:debug'; // enables lib debugging statements

    exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
      const agent = new WebhookClient({ request, response });
      console.log('Dialogflow Request headers: ' + JSON.stringify(request.headers));
      console.log('Dialogflow Request body: ' + JSON.stringify(request.body));

      function welcome(agent) {
        agent.add(`Welcome to my agent!`);
      }
     function testing(agent){
       agent.add(`testing works`);
     }
      function fallback(agent) {
        agent.add(`I didn't understand`);
        agent.add(`I'm sorry, can you try again?`);
      }

      // Run the proper function handler based on the matched Dialogflow intent name
      let intentMap = new Map();
      intentMap.set('Default Welcome Intent', welcome);
      intentMap.set('Default Fallback Intent', fallback);
      intentMap.set('test',testing);  //testing handler
      // intentMap.set('your intent name here', googleAssistantHandler);
      agent.handleRequest(intentMap);
    });
>
But when i deployed i got this error

    Webhook call failed. Error: UNKNOWN
Response
<pre>
   {
      "responseId": "5dd7232c-e92e-4039-bbc6-9e9bf826bb3e-b4ef8d5f",
      "queryResult": {
        "queryText": "hey i am testing",
        "parameters": {},
        "allRequiredParamsPresent": true,
        "fulfillmentMessages": [
          {
            "text": {
              "text": [
                ""
              ]
            }
          }
        ],
        "outputContexts": [
          {
            "name": "projects/smart-library-55e4d/agent/sessions/4bd5533e-0465-02e4-45d3-1bd3383b21d5/contexts/__system_counters__",
            "parameters": {
              "no-input": 0,
              "no-match": 0
            }
          }
        ],
        "intent": {
          "name": "projects/smart-library-55e4d/agent/intents/0eadac8a-c487-4f7e-92ce-18e64f113e3c",
          "displayName": "test"
        },
        "intentDetectionConfidence": 1,
        "languageCode": "en"
      },
      "originalDetectIntentRequest": {
        "payload": {}
      },
      "session": "projects/smart-library-55e4d/agent/sessions/4bd5533e-0465-02e4-45d3-1bd3383b21d5"
    }
</pre>

**Comment by Fleker** [comment]
If you check the Firebase Functions console do you see any errors?

**Comment by mrinal2305** [comment]
> If you check the Firebase Functions console do you see any errors?

No error

**Comment by Fleker** [comment]
The error says the webhook call failed. Does the function run at all?

**Comment by miguelrochefort** [comment]
I have the same issue. Did you find a solution?

**Comment by slomeks** [comment]
Same here.

**Comment by slomeks** [comment]
Not a solution per se - rather workaround. But finally made it work.
Deleted the agent in Dialogflow and created a new one from scratch.

**Comment by StrikingThirteen** [comment]
I have followed the codelab one instructions pretty closely.
The digital flow api is the one available currently (V2). I'm seeing the following issue:

`Failed to parse Dialogflow response into AppResponse because of invalid platform response: Could not find a RichResponse or SystemIntent in the platform response for agentId: 862967e8-4384-403b-aad9-edd16bb0a729 and intentId: ff89b919-3363-43b5-a9af-d9b37ea13e22. WebhookStatus: code: 2 message: "Webhook call failed. Error: UNKNOWN." ..`

**Comment by slomeks** [comment]
@StrikingThirteen Not really - everything as in the tutorial. The only thing to remember is to use the same name of intent in Dialogflow and in the inline function.
If you continue having the issue - pls consider reaching out to Support. They are really helpful.
Good luck!

**Comment by taycaldwell** [comment]
This error is not reproducible when following the [Build Actions for the Google Assistant (Level 1)](https://codelabs.developers.google.com/codelabs/actions-1/) instructions in entirely.

Please ensure your intent name matches the name of the intent handler defined in the fulfilment code.
