### ISSUE TITLE
step 6 - cannot toggle Inline Editor

### ISSUE THREAD

**Issue by dakshshah14** [actions-on-google/codelabs-nodejs#65]
<img width="1419" alt="Screen Shot 2020-03-18 at 5 42 10 PM" src="https://user-images.githubusercontent.com/5555534/77014291-f4d9ec00-693f-11ea-983a-546f3c91ac5a.png">

**Comment by taycaldwell** [comment]
Hi @dakshshah14,

Did you try refreshing the page and waiting a few minutes for the Google Cloud resources to finish provisioning, as suggested in the error message provided?

**Comment by dakshshah14** [comment]
yup did that. didn't work for half an hour. After that, the time had run out and i kept hitting the paywall. even that got stuck after step 1.

**Comment by dakshshah14** [comment]
seems to be solved. Thanks
